Starting in Beer Garden 2.1.0, it is possible to tell your plugins how to log from the Beer Garden application itself. Beer Garden provides a new api (`/api/v1/config/logging`) which will respond with a logging configuration that plugins can optionally use. Checkout our Swagger documentation for the complete details of this new endpoint.

This allows you to do one-time configuration of a logger in Beer Garden configuration files and propagate that logging configuration to all of your plugins. To use it, you simply add the following to your entry point.

[source,python]
----
import sys
from brewtils import get_connection_info
from brewtils.log import configure_logging

# Your client definition Here

if __name__ == "__main__":
    connection_info = get_connection_info(sys.argv[1:])
    configure_logging(system_name='my_system', **connection_info)
    # Init your plugin as normal.
----

This tells Beer Garden to setup a root logger based on what is returned from the endpoint at `api/v1/config/logging`. Checkout the link:../../configuration[configuration section] for more information on how to configure this. This is mostly useful for remote plugins.
