#!/bin/bash

echo "Building static files using awestruct..."

GIT_DIR="${OPENSHIFT_HOMEDIR}git"
APP_GIT_DIR="${GIT_DIR}/${OPENSHIFT_APP_NAME}.git"
APP_GIT_LOG_DIR="${APP_GIT_DIR}/logs"
GIT_LOGFILE="${APP_GIT_LOG_DIR}/HEAD"
export LAST_COMMIT_DATE=$(tail -1 ${GIT_LOGFILE} | cut -d' ' -f7)

cd $OPENSHIFT_REPO_DIR
bundle exec ./vendor/bundle/ruby/2.3.0/bin/awestruct --source-dir source --output-dir public.new -P production
mv public public.old
mv public.new public
rm -rf public.old
