image: ruby:2.7.2

cache:
  key: bundlecache
  paths:
    - .cache/bundler

stages:
  - build

pages:
  stage: build

  variables:
    NOKIGIRI_USE_SYSTEM_LIBRARIES: "true"

  script:
    - bundle config set mirror.https://rubygems.org/ $GEM_MIRROR
    - bundle config set path .cache/bundler
    - bundle install
    - rake gen[gitlab]

  artifacts:
    paths:
      - public

