image: ruby:2.7.2

cache:
  key: bundlecache
  paths:
    - .cache/bundler

stages:
  - prep
  - build

banners:
  stage: prep

  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $BANNER_HEADER && $BANNER_FOOTER

  script:
    - cat "$BANNER_HEADER" > ./_layouts/header.html.slim
    - cat "$BANNER_FOOTER" > ./_layouts/footer.html.slim

  artifacts:
    paths:
      - ./_layouts/header.html.slim
      - ./_layouts/footer.html.slim

pages:
  stage: build

  tags:
    - pages

  rules:
    - if: $CI_COMMIT_BRANCH == "master"

  variables:
    NOKIGIRI_USE_SYSTEM_LIBRARIES: "true"

  script:
    - bundle config set mirror.https://rubygems.org/ $GEM_MIRROR
    - bundle config set path .cache/bundler
    - bundle install
    - rake gen[gitlab]

  artifacts:
    paths:
      - public

