= Beer Garden
Logan Jones <https://github.com/loganasherjones[@loganasherjones]>;
:idprefix:
:page-layout: about
// URIs:
:uri-repo: {git_group_uri}/beer-garden
:uri-doc-repo: {git_group_uri}/beer-garden.io
:uri-license: {uri-repo}/blob/master/LICENSE.md
// Images
:imagesdir: {image_dir}/images


Imagine if writing composable software services was as easy as writing a class in your favorite language with your favorite text editor. And sharing was as easy as running your main method.

__It **can** be.__

That's the main idea behind Beer Garden. So much of software development is tangled in the weeds of standing up services, getting messages from one component to another, creating UIs, writing documentation, and concurrently supporting multiple versions. We want to change that.

Beer Garden makes it easy to turn your functions into REST interfaces that are ready for production use, in a way that's accessible to anyone that can write a function. It creates all the boilerplate and infrastructure needed to turn that function into a type-safe, discoverable REST interface and an easy-to-use webform-based UI:

video::demo.webm[alt="Preview Plugin to HTML Form Screenshot",width=100%, options="autoplay, loop"]


== Next Steps
If this looks interesting and you're ready to jump in then the link:docs/startup/quickstart[Quickstart] is for you!

On the other hand, if you're still unsure of exactly what Beer Garden is and what it can do for you then take a look at link:docs/startup/what-is-beergarden[What is Beer Garden?] It has more overview information that can help you decide if Beer Garden is right for you.

Finally, if you're looking for specific info, trying to figure out how to do something, or wondering if Beer Garden can do the neat thing you thought of the best place to look is the link:docs[User Manual].

CAUTION: We're excited to announce Beer Garden v3 has been released! Check out the link:docs/app/upgrading[Application] and link:docs/plugins/upgrading[Plugin] upgrade guides if you'd like to learn more.

== Getting Help

We want Beer Garden to make your life easier. If there's anything that's unclear or difficult (or broken!) we want to know about it! Here are the best ways to get in touch with us:

* Talk to us in {chat_uri}[Gitter]
* Submit an issue to the {issues_uri}[Issue Tracker]


=== Contributing

Beer Garden is open-source, and in the spirit of open-source software _everyone_ is encouraged to help improve this project. If you discover errors or omissions in the source code, documentation, or website content please don't hesitate to submit an issue or open a merge request. New contributors are always welcome!

Check out the link:docs/contributing/[Contributing] guide to get started.

Here are some ways __you__ can contribute:

* Use the pre-release (development) versions
* Report bugs
* Suggest new features
* Write or edit the documentation
* Write code - _No patch is too small_


=== Credits

A huge shout-out to https://asciidoctor.org[the Asciidoctor Project]. This website is built with AsciiDoctor and was heavily influenced by the Asciidoctor website. It really is the best way to write documentation and we highly recommend you check it out!

This website is hosted by https://pages.github.com/[GitHub Pages]. It makes deployment easy and cheap. You can use it for blogs or documentation like this. Definitely take a look!


=== Copyright and Licensing

Free use of this software is granted under the terms of the MIT License. See the {uri-license}[LICENSE] file for details.
