= beer-garden.io

The documentation for
https://github.com/beer-garden/beer-garden/[beer-garden]
project. Composed in AsciiDoc, styled by Bootstrap, baked with Awestruct and
published by Github Pages.


For instructions on how to install Awestruct and its dependencies, refer to
the section xref:install-awestruct[Install Awestruct] below.

== Preview the site locally

To preview the site locally, simply run the default rake build task:

  rake

The default rake build task is +preview+, so you're effectively typing:

  rake preview

the +preview+ task is just a short way of invoking Awestruct in development
mode directly:

  awestruct -d --source-dir source --output-dir public

Now visit http://localhost:4242 to preview the site

To rebuild the site from a clean state, pass the +--force+ flag to the +preview+
task:

  rake preview[--force]

You can pass any flag through to Awestruct using the syntax in the previous
command.

If you just want to generate the site, run:

  rake gen

=== Add and commit files

Add new files (such as new tutorials, etc):

  git add tutorials/my-tutorial.adoc

or add all the new files in a directory:

  git add tutorials/

Commit all files marked to be committed, including new files that were
just added:

  git commit -m "your message here"

Make sure there are no files that are "untracked" or "modified":

  git status

You should see:

  nothing to commit (working directory clean)

Now you are ready to deploy

== Deploying the site to Github Pages

Just run

  git fetch origin gh-pages
  rake deploy
  git push origin gh-pages


== Install Awestruct

First, install https://rvm.io/rvm/install[RVM].

Next, simply `cd` into this directory.

  cd /path/to/beer-garden.io/

This will activate `rvm` for `ruby-2.3.1@beer-garden.io`

At this point, you could install Awestruct directly, but since the site build
has some additional dependencies, it's best to let bundler handle the
installation. Bundler will also ensure that you are using the correct versions
of each gem when you run Awestruct.

  bundle install

You're now Awestruct!
