= Native Python Installation
:page-layout: docs

This guide will take you through step-by-step installation instructions via python.

== Prerequisites

A Beer Garden Python installation requires a few things to work:

* Python 3.7+
* Connectivity to MongoDB 3.2+
* Connectivity to RabbitMQ

Installing these is outside the scope of this documentation, so please refer to their installation instructions for
detailed installation instructions/configuration.

== Installing Beer Garden ==

We host `beer-garden` on PyPi. You can install it via:

[source,subs="attributes"]
----
pip install beer-garden
----

You can generate a configuration file by running:

[source]
----
generate_config -c config.yaml
----

This will place a config file in `config.yaml`. Feel free to edit this file however you would like. Most of the
defaults are likely fine for now, though you will need to update connection information for your message broker
and database. Read more about the beergarden configuration in the link:/docs/app/configuration[configuration section.]
Then you can startup the application and point to that configuration.

[source]
----
beergarden -c config.yaml
----

Everything that is in the `config.yaml` can be overriden from the command-line. See more information with:

[source]
----
beergarden --help
----

== Installing the Beer Garden UI

The Beer Garden UI is a separate javascript application that does not get installed with the python backend. To run the UI, it is recommended that you following the directions in one of the sections below:

* link:../docker/[Docker / Docker Compose]
* link:../git/[Development Setup]
