= Python Plugin Guide (Local)
:page-layout: docs
:includedir: _includes
:uri-install-guides: ../../installation-guides/

// TODO Should we update this to include Namespace?

The goal of this section is to help you write a local plugin from scratch. In order to write local plugins there are a few things that you need.

== Prerequisites

include::{includedir}/prereqs.adoc[]

NOTE: You'll also need to be able to write to the plugins directory of the Beer Garden you plan on using.

Now you're ready to start writing your plugin.

== Anatomy of a plugin

The anatomy of a plugin is pretty simple. If you are familiar with writing python libraries, this directory structure should look very familiar. A normal plugin will look something like this:

    my_plugin/
        |
        | - beer.conf
        | - setup.py
        |   my_plugin/
        |       |
        |       |  - __main__.py
        |       |  - __init__.py

== Hello World!
Plugins are just classes with methods that you would like to expose. This section will walk you through setting up a plugin that exposes the classic 'Hello, World!' functionality.

=== Setting up

Using the structure shown in <<Anatomy of a plugin>>, create the necessary empty files and folders.  For this example use `hello_world` for the folders labeled `my_plugin`.

=== Write the code

Use your favorite text editor to open up `\\__main__.py` and add the following:

include::{includedir}/hello-world-client.adoc[]

Once we have the client, we now need to create our entry point. Let's open back up the previous file and add the following:

include::{includedir}/hello-world-local-entry-point.adoc[]

=== Configure your plugin
Alongside, not inside, our `hello_world` folder we need to create two more files: `beer.conf` and `setup.py`.  `beer.conf` is a special configuration file that Beer Garden uses to determine important information about your plugin.

[source,python]
.beer.conf
----
PLUGIN_ENTRY='-m hello_world'
----

Now that you've written your code and `beer.conf`, you'll need to find a way to package your software. Python uses `setuptools` to do this. Let's start with a simple `setup.py`. This file is standard python, but we will go over an easy configuration first:

[source,python]
.setup.py
----
from setuptools import setup

setup(
    name="hello-world",
    version="1.0.0.dev0",
    description="Prints 'Hello, World'",
    packages=["hello_world"],
    install_requires=["brewtils"],
)
----
//
//Since our files may or may not be in a correct package, we also are going to add the following to `MANIFEST.in`. Since Beer Garden plugins are expected to include a `beer.conf` file in their distributions, the `MANIFEST.in` is python's way of including that file in the source build. You can simply include it as follows:
//
//[source]
//.MANIFEST.in
//----
//include beer.conf
//include main.py
//----
//
// TO-DO: Confirm that this is right? When setup with the include beer.conf line, the file still isn't in the tar
=== Creating your distribution

Once you are done configuring everything, all you need to do is tar
[source]
----
python setup.py sdist
----
// Relies on the previous to-do
=== Deploying your plugin

Take your `tar.gz` file, and copy it to the plugins directory of Beer Garden. The default location for RPMs is `/opt/beer-garden/plugins` but varies based on your installation methods. Once copied, you simply need to untar/compress it:

[source]
----
cp dist/my-plugin-0.0.1.tar.gz /opt/beer-garden/plugins/
cd /opt/beer-garden/plugins/
tar -zxvf my-plugin-0.0.1.tar.gz
----

Now go to the Beer Garden GUI under `Administration -> Systems Management` and click `Rescan System Directory` in the top right. This will instruct Beer Garden to scan the plugins directory for new plugins and start them. You should see your plugin appear. Once it is up, you can go to `Systems` then your system and see the command `hello_world`! Click `Make it Happen!` then `Make Request` to see your plugin in action.

That's it!

== Anatomy of a plugin

The only thing in this directory structure that should look non-standard is the `beer.conf` file. But for posterity's sake, let's examine each of these files/directories a little bit more closely.

=== beer.conf

The `beer.conf` file is a minimal configuration file that specifies to Beer Garden how to configure and start up the plugin. The beer.conf file has minimal options. Below is an expanded beer.conf file that explains all the possible values.


    NAME = "my-plugin"                           # The name of your plugin
    DISPLAY_NAME = "My Plugin"                   # The name shown in the GUI
    VERSION = "0.0.1"                            # The version of your plugin
    DESCRIPTION = "My plugin does cool stuff"    # A description of your plugin
    PLUGIN_ENTRY = 'main.py'                     # Defines way to run the plugin
    INSTANCES = ["i1", "i2"]                     # The instances to define
    PLUGIN_ARGS = ['arg1']                       # Command line arguments to each instance
    ENVIRONMENT = {'MY_PASSWORD':'sup3r$ecret'}  # Environment variables
    REQUIRES = ['foo']                           # Defines relationship to 'foo' plugin


=== MANIFEST.in

To developers who have never written a complicated egg before, the `MANIFEST.in` may be something new. Since Beer Garden Plugins are expected to include a `beer.conf` file in their distributions, the `MAINFEST.in` is python's way of including that file in the source build. Generally speaking (unless you have additional requirements that are not python packages) you can simply include the `beer.conf` and your plugin executable in the MANIFEST. Most `MANIFEST.in` files look like the following:

    include beer.conf
    include main.py


This basically says "include main.py and beer.conf" in my source distribution.

=== main.py

___The main.py does not have to be called main.py___, but it is whatever name you gave to your `PLUGIN_ENTRY` entry in the `beer.conf` file and must be included in the source distribution. This is what starts up the plugin and keeps it running.

=== setup.py

The `setup.py` file should be very standard. Customize this as you would customize any `setup.py` file for packaging python eggs.

=== my_plugin/*

Everything in the `my_plugin/` directory is specific module level code you would like to include in your distribution. You can organize your library however makes sense to you. The code underneath here has little if anything to do with Beer Garden.  The only thing that you'll see that Beer Garden requires is some type of client that has been decorated with utilities from {brewtils_docs_uri}[brewtils.]

That's all there is to plugin layouts!

== Plugin Configuration

include::{includedir}/beer-conf.adoc[]

== Exception Handling

include::{includedir}/exceptions.adoc[]

== Logging

For Local plugins, Beer Garden will attempt to make decent decisions about where it should log. For example, if Beer Garden is configured to log to `STDOUT` or `STDERR` then your plugin will log there as well. If, however, Beer Garden is configured to log to a file (the default behavior for RPMs), then it will give each unique plugin its own log file. If you would like to log, you can either print to `STDOUT` or `STDERR`. The `LocalPlugin` will take care of everything else.

INFO: Use STDOUT or STDERR for logging

You can use the python logging to log to stderr with your own format if you'd like via:

[source,python]
----
import logging
logger = logging.basicConfig(level=logging.INFO,
                             format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
logger.info("foo")
----

You can also just use print:
[source,python]
----
print "foo"
----

If you choose to use print and have a long running process and you would like the log statements to come out as they happen, then you will need to flush the stdout yourself.

[source,python]
----
def my_long_running_method(self):
  time.sleep(1000)

@command
def do_something(self):
  print "I'm in do something!"
  sys.stdout.flush()
  my_long_running_method()
----

Otherwise, if you are using print, the `LocalPlugin` will flush once your method has been completed.

== External Logging

include::{includedir}/external-logging.adoc[]

== Plugins with external dependencies

If your plugin requires external dependencies (python libraries or otherwise) you are required to include these in your source distribution. Unfortunately, this means some additional work for you. Luckily, if all you require are python dependencies, pip has an easy way to include these.

You can do whatever you would like to get these files into your distribution, here is simply one of the examples. Let's say you require the Fabric dependency. You would add it to your requirements.txt:

```
bg-utils==0.0.4
Fabric==1.8
```

Then if you wanted to include this in your source distribution you could install it to a directory:

```
mkdir vendor
pip install Fabric -t vendor/
```

Now, you need to include this in your source distribution by modifying your `MANIFEST.in`

```
include beer.conf
include main.py
graft vendor
```

This ensures that everything under vendor will be included in your source distribution. Finally, since you likely want this to be on your load path, you'll need to modify your `beer.conf` to include a new place to look for this information:

```
ENVIRONMENT={
'PYTHONPATH': '$BG_PLUGIN_PATH/vendor/lib/python2.7/site-packages'
}
```

This will allow you to successfully load Fabric.

== Making your plugin more descriptive
include::{includedir}/descriptive-plugin.adoc[]

== Customizing Command Form
include::{includedir}/custom-display.adoc[]
