
=== Event Notifications

Sometimes, particularly if you're integrating with Beer Garden, it can be helpful to know when certain things happen. To make this process as easy as possible Beer Garden supports the concept of _event notifications_.

Events are generated whenever any of the following events occur:

==== Request Based Events
    REQUEST_CREATED
    REQUEST_STARTED
    REQUEST_UPDATED
    REQUEST_COMPLETED
    REQUEST_CANCELED

==== Instance Based Events
    INSTANCE_INITIALIZED
    INSTANCE_STARTED
    INSTANCE_UPDATED
    INSTANCE_STOPPED
    INSTANCE_STOP_REQUESTED
    INSTANCE_START_REQUESTED

==== System Based Events
    SYSTEM_CREATED
    SYSTEM_UPDATED
    SYSTEM_REMOVED
    SYSTEM_RESCAN_REQUESTED
    SYSTEM_RELOAD_REQUESTED

==== RabbitMQ Based Events
    QUEUE_CLEARED
    ALL_QUEUES_CLEARED

==== Garden Based Events
    GARDEN_CREATED
    GARDEN_UPDATED
    GARDEN_REMOVED
    GARDEN_STARTED
    GARDEN_STOPPED
    GARDEN_UNREACHABLE
    GARDEN_ERROR
    GARDEN_NOT_CONFIGURED
    GARDEN_SYNC

==== Entry Point Based Events
    ENTRY_STARTED
    ENTRY_STOPPED

==== Job Based Events
    JOB_CREATED
    JOB_DELETED
    JOB_PAUSED
    JOB_RESUMED

==== Environment Based Events
    PLUGIN_LOGGER_FILE_CHANGE


==== Event Structure

Events will always be well-formed JSON. Here's an example of an event:

[source,json]
.event.json
----
{
    "name": "REQUEST_CREATED", <1>
    "garden": "default", <2>
    "timestamp": 1521126132897, <3>
    "error": None, <4>
    "error_message": None, <5>
    "metadata": { <6>
        "entity_url": "https://this.is.beergarden:443/api/v1/requests/5aaa8af45991735bf1a6c123",
        "public_url": "https://this.is.beergarden:443/"
    },
    "payload": { <7>
        "id": "5aaa8af45991735bf1a6c123",
        "command": "say",
        "system": "echo",
        "system_version": "1.0.0",
        "instance_name": "default"
    },
    "payload_type": "Request" <8>
}

----
<1> All events will have a name
<2> All events will have the Garden name that it is coming from
<3> All events will have a timestamp (milliseconds since the epoch)
<4> All events will have an error flag (boolean, None being equivalent to False)
<5> All events that have an error flag set will have an Error Message as a String
<6> Events may have a metadata field. This will contain 'extra' useful information, but will normally include at least the the public url of the Beer Garden that generated the Event. Events that relate to a specific entity will also include a url that can be used to retrieve the full entity definition.
<7> Events may have a payload. The specific data included will vary based on event type.
<8> Events may have a payload. This field will define what type model to utilize to parse the JSON.

////

==== Enabling Events

Events are disabled by default, but they can be published to a RabbitMQ topic exchange and/or persisted to MongoDB.

===== Mongo
To perist events to Mongo set the ``event_persist_mongo`` configuration option in Brew view to ``True``:

[source,json]
.config.json
----
{
    "event_persist_mongo": True
}
----

===== RabbitMQ
To publish events to RabbitMQ set the ``event_amq_virtual_host`` and ``event_amq_exchange`` configuration options to valid values.

[source,json]
.config.json
----
{
    "event_amq_virtual_host": "/",
    "event_amq_exchange": "beergarden_event"
}
----

WARNING: Beer Garden doesn't create an exchange for events. While you _could_ use the normal Beer Garden request exchange we recommend you don't. Instead, you should create a separate exchange. Check the RabbitMQ docs for instructions on how to do this.

To consume from RabbitMQ, you'll need to create a queue on the same virtual host as ``event_amq_virtual_host`` and then bind that queue to a routing key on the ``event_amq_exchange``. To receive all events you can bind to the ``#`` routing key. If you want to filter which events your queue will receive there are some rules about how Beer Garden assigns routing keys to events:

* The default routing key is 'beergarden'. Events that don't fit any other rules will use this.
* Request events will have a routing key of the form ``request.<system_name>.<mangled_system_version>.<instance_name>``. Since RabbitMQ treats '.' as a delimiter the system version is mangled to replace all instances of '.' with '-'. So an example would be ``request.echo.1-0-0.default``. If you were only interested in requests related to the 'echo' system you could bind your queue to the ``request.echo.#`` routing key.

////

==== Publishing Custom Events

WARNING: This is a beta capability

It's possible to publish your own events. Just POST a valid Event to the ``/api/vbeta/events`` endpoint. The brewtils EasyClient ``publish_event`` method can help with this.
