= V3 Architecture Work
:page-layout: docs

In addition to some cool new features, version 3 of Beer Garden aims to create formalized internal APIs. We have found that as the application has grown, we've needed some more formal structure to define the subsystems that make up Beer Garden. This is a living document as we formalize the internal components of Beer Garden.

This document is intended more for Beer Garden developers than just users. It attempts to explain the main design concepts of Beer Garden rather than the external facing API. These APIs may change from version to version but they should not represent an interruption to our main APIs. For more information on the actual API, checkout that documentation.

== Overview

The end-goal of this overview section is to provide a high-level picture of the breakdown of Beer Garden into its subsystems. Essentially, it should be an architecture diagram.

There are some words in this document that are worth defining formally to avoid any confusion.

Subsystem:: While we figure out what (if anything) needs to live in a separate process, this is the word we are using to describe a function that Beer Garden needs to provide. It does not insinuate *anything* about the code.

Each subsystem will have its own section with the following information:

1. A high level description of the reason the subsystem exists.
2. A formal API contract
3. A list of subsystem dependencies

== Golden Rules

These are rules that we have come up with during the design process that have fairly large implications. We use them as guiding elements when making additional design decisions. They are **not** set in stone, but should be carefully considered before change.

1. System + Instance has a one-to-one mapping with a queue.
2. Entries in the database are supposed to be there, we may need to add additional information based on monitoring, but we should not need to remove it.


== Marshaler

The marshaler subsystem is in charge of object serialization and deserialization. It is in charge of taking storage or transmission versions of an object (e.g. JSON), converting it into an internal representation of the same object and vice versa.

=== Marshaler API

CAUTION: This API is not finalized. It is just a working copy of where we are so far.

* `marshal(obj: Any, output_format="json": str)` - Take the object and return a serialized version of it. If the output is a non-binary format (e.g. JSON) then the output will be a utf-8 encoded string. The default format is JSON.
* `unmarshal(data: Any, klazz: Union[str,object])` - Take the storage/transmission data representation and turn it into an instance of the klazz. 

If the data is invalid for any reason, the marshaler is responsible for raising an error indicating what the underlying problem was.

=== Marshaler Dependencies

None.

== Configuration

The configuration subsystem is responsible for:

* Loading configuration files
* Migration configuration files between Beer Garden versions
* Getting configuration values

=== Configuration API

CAUTION: This API is not finalized. It is just a working copy of where we are so far.

* `load(args: List[str])` - Called once on startup. Args are command-line arguments. Loads configuration from environment variables, command-line arguments and configuration file.
* `migrate(filename: str)` - Migrate a previous configuration file to the new configuration specification.
* `get(key: str)` - Get a specific configuration value for the given key. All defaults should be specified in the specification and not in calling code.

=== Configuration Dependencies

None.


== Auth[nz]

The auth service is responsible for authentication and authorization. Essentially, it is responsible for providing a yes or no answer to the question, "Can User X do Action Y on Resource Z?". In all likelihood, this subsystem will actually be broken down into additional subsystems. As a result, it will probably need its own section describing the internals of the Auth[nz] service.

**Notes:** (These can be delete once finalized)

* Down stream systems do not make additional auth[nz] decisions.
* Does not forward roles or tokens.

=== Auth[nz] API

CAUTION: This API is not finalized. It is just a working copy of where we are so far.

* `authenticate(user_id: Any)` - Return an internal Beer Garden user if it could resolve the user, error otherwise.
* `authorize(user: User, action: dict, klazz: Union[str,object])` - Return a `True` if the user is authorized to perform the action on the given class. I'm not in love with `action` being a `dict`, and could easily be convinced that each action needs to be a particular object.

=== Auth[nz] Dependencies

* Persistence Layer - Will need to query the database to determine permissions/users.
* Marshaler - Will need to convert users into the internal user objects.

== Persistence Layer

The persistence layer is responsible for:

* Querying the database
* Create, Update, and Delete operations on the database
* Publishing events whenever *anything* in the database changes

This layer should allow us to swap out databases without the rest of the system knowing/caring. Objects coming out of the persistence layer should have nothing to do with the underlying data store. Access to the persistence layer assumes you have already authenticated/authorized a user.

The persistence layer is also responsible for saving/retrieving files.

=== Persistence Layer API

CAUTION: This API is not finalized. It is just a working copy of where we are so far.

* `query(???)` - Not sure on this API. It might be worth looking at GraphQL for this solution. We are essentially looking for a DB agnostic query language and I think GraphQL provides that. I'm just not sure how difficult that will be to actually implement
* `create(obj: Any)` - Create the object given. The object's class will be inspected to determine the correct place to save it.
* `delete(obj_or_id: Union[str, object])` - Delete the resource identified by the ID. Could also be the actual object.
* `update(obj: Any)` - Update the given object such that all attributes on the obj replace the current values in the database.

=== Persistence Layer Dependencies

* Marshaler - Will need to convert internal models into database representations and back.
* Event Engine - Will need to publish events on `create`, `update`, and `delete`

== Plugin State Manager

The PSM subsystem is responsible for:

* Plugin Registration
* Plugin Monitoring
* Plugin Removal

=== Plugin State Manager API

CAUTION: This API is not finalized. It is just a working copy of where we are so far.

* TODO: Fill this out.

=== Plugin State Manager Dependencies

* TODO: Fill this out

== Queue

The queue subsystem is responsible for:

* Queue CRUD operations
* Publishing requests

=== Queue API

CAUTION: This API is not finalized. It is just a working copy of where we are so far.

* TODO: Fill this out.

=== Queue Dependencies

* TODO: Fill this out

== Event

The event subsystem is responsible for:

* Internal events
* Publishing external events

=== Event API

CAUTION: This API is not finalized. It is just a working copy of where we are so far.

* TODO: Fill this out.

=== Event Dependencies

* TODO: Fill this out

== Local Plugin

The local plugin subsystem is responsible for:

* Monitoring a directory
* Monitoring local plugin processes
* Load a plugin from disk

One note here is that it does *process* monitoring **not** plugin monitoring.

=== Local Plugin API

CAUTION: This API is not finalized. It is just a working copy of where we are so far.

* TODO: Fill this out.

=== Local Plugin Dependencies

* TODO: Fill this out

== Request

The request subsystem is responsible for:

* TODO: Fill this out.

=== Request API

CAUTION: This API is not finalized. It is just a working copy of where we are so far.

* TODO: Fill this out.

=== Request Dependencies

* TODO: Fill this out

== Scheduler

The scheduler subsystem is responsible for:

* TODO: Fill this out.

=== Scheduler API

CAUTION: This API is not finalized. It is just a working copy of where we are so far.

* TODO: Fill this out.

=== Scheduler Dependencies

* TODO: Fill this out

== SUBSYSTEMNAME

The SUBSYSTEMNAME subsystem is responsible for:

* TODO: Fill this out.

=== SUBSYSTEMNAME API

CAUTION: This API is not finalized. It is just a working copy of where we are so far.

* TODO: Fill this out.

=== SUBSYSTEMNAME Dependencies

* TODO: Fill this out
