title: Beer Garden
description: A powerful framework for converting your functions into composable, discoverable services.
author: Beer Garden Project
blog_path: /news
local_tz: America/New_York
disqus: beer-garden
disqus_generate_id: true
disqus_developer: true
asciidoctor:
    :safe: :unsafe
    :attributes:
        sitename: beer-garden.io
        base_url: ''
        ctx_path: ''
        idprefix: ''
        idseparator: '-'
        sectanchors: ''
        attribute-missing: 'warn'
        source-highlighter: 'coderay'
        relfileprefix: '../'
        outfilesuffix: '/'
        icons: font
        iconfont-remote: false
        iconfont-name: font-awesome
        webfonts: false
        git_uri: https://github.com
        git_ssh_uri: git@github.com:beer-garden/beer-garden.git
        git_group_uri: https://github.com/beer-garden
        chat_uri: https://gitter.im/beer-garden-io/Lobby
        issues_uri: https://github.com/beer-garden/beer-garden/issues
        brewtils_docs_uri: https://brewtils.readthedocs.io
        bg_utils_docs_uri: https://bg-utils.readthedocs.io
        imagesdir: './images'
# base_url: ''
# ctx_path: ''
# interpolate: false
haml:
    :ugly: true
slim|html:
    :format: :html

profiles:
    development:
        base_url: ''
        image_dir: '.'
    gitlab:
        base_url: '/beer-garden.io'
        image_dir: './beer-garden.io'
        scss:
          line_numbers: false
          style: compressed
    github:
        base_url: ''
        disqus_developer: false
        image_dir: '.'
        google_analytics_account: UA-113442079-2
        google_analytics:
          account: UA-113442079-2
        scss:
          line_numbers: false
          style: compressed
          # Don't think this is necessary, we let CI do the deploying
          #deploy:
          #  host: github_pages
          #  branch: gh-pages
