== Example 1: Hello Beer Garden
:includedir: ../python/_includes

This section will walk you through creating a basic example plugin. We'll start with a simple Python script (hello, world) and turn it into a functional plugin.

=== Prep

We'll begin by constructing a basic "Hello, World" program. Create and open a file called `plugin.py` and write the classic:

[source,python]
.plugin.py
----
def main():
    print("Hello, World!")


if __name__ == "__main__":
    main()
----

This can be run from the command line like this:

[source,bash]
----
python plugin.py
----

=== Organize

Plugins need to be organized around a class, so let's do some light reorganization before converting this to a plugin:

[source,python]
.plugin.py
----
class Greeter:
    def greet(self, greeting="Hello, World!"):
        print(greeting)


def main():
    greeter = Greeter()
    greeter.greet()


if __name__ == "__main__":
    main()
----

We've moved the `print` call into a `greet` method, and we now call that method in `main`. We've also added an argument to the `greet` method to make our greeting more dynamic.

We can still run the file like before, though:

[source,bash]
----
python plugin.py
----

=== Plugify

Now that the prep work is done we can convert this to a Beergarden plugin.

[source,python]
.plugin.py
----
from brewtils import command, Plugin


class Greeter:
    @command <1>
    def greet(self, greeting="Hello, World!"):
        print(greeting)


def main():
    plugin = Plugin(name='greeter', version='1.0.0')
    plugin.client = Greeter()
    plugin.run()


if __name__ == "__main__":
    main()
----
<1> The `@command` decorator marks this method as a Command to make available

Let's review the changes here:

* We've added a decorator to the `greet` method. This tells Beergarden to expose that method as a Command.
* We now create a `Plugin` object, passing in a name and version. We then assign an instance of our `Greeter` class as its `client`. Finally, we `run` the Plugin.

=== Run the plugin

To run our plugin now we need to tell it how to connect to our Beergarden application. We can do that by passing in the appropriate command line arguments. This tutorial assumes your application is running on `localhost`:

[source,bash]
----
python plugin.py --bg-host localhost --no-ssl-enabled
----

The plugin should now start and display log statements showing the plugin registering with Beer Garden. Congratulations! You've just deployed your first plugin!

=== Use the code

At this point you should see your plugin on the `Available Systems` page in `Brew View`. Click the big blue `Explore hello_world commands` button to see a list of all commands available for the Plugin you made.

As part of this tutorial the only command listed should be the `say_hello` command because we only defined one command. Click the `Make it Happen!` button to go to the page for that command.

The command page is where you can specify options and customization for individual executions of that command. Since we didn't define any options (this command always prints 'Hello World!') the only customization available is the comment field. You can add free-form text here and it will be included as part of the request you're generating.

Are you ready? Click the `Make Request` button when you're ready.

Making a request takes you to the Request page for the request you just generated. You can see the unique ID as part of the page title. You should see the status start as `IN PROGRESS` and then change to `SUCCESS` once the request completes. Also notice that the output changes when the request is finished.

If you didn't catch those changes on the first try, don't worry. Use the `Pour it Again` button in the top-right corner to go back to the command screen you just left. From there you can use the `Make Request` button to make another request.

NOTE: This command doesn't have any parameters, but for commands that do the `Pour it Again` button will default them to exactly how they were for the original request.

=== Stop the code
The best way to stop a plugin is to use the 'Systems Management' page to send a stop message. In `Brew View` find the `Systems Management` option under the `Administration` menu. Then click the stop icon next to the `hello-world` listing.

You should see your plugin log that it has terminated and stop executing, and if you go to the main page in `Brew View` you should see the `hello-world` plugin is 'STOPPED'.

NOTE: You can also use Ctrl-c to stop the plugin from the terminal. This works, but it doesn't tell Beer Garden that the plugin is stopping. You'll still see the plugin terminate and stop executing, but the status in `Brew View` will still be 'RUNNING'. After a short period the status will change to 'UNRESPONSIVE'.
