= Beer Garden 101

:page-layout: docs
:guide_dir: ../plugins/python
:uri-install-guides: ../../installation-guides/
:imagesdir: ../../images

This course is designed to take a developer who is familiar with Python and
bring them up to speed on how to create and execute a Plugin on Beer Garden.

== Overview of Beer Garden

Beer Garden is targeted to help developers break the barrier between python
scripts and software. So much of software development is tangled in the weeds
of standing up services, getting messages from one component to another,
creating UIs, writing documentation, and concurrently supporting multiple
versions. We wanted to change that. Beer Garden makes it as easy as running
the main method.

Development of the Beer Garden framework is written in Python for Python. It has been a
multi-year effort to bring Beer Garden to the state it is today. It is constantly
evolving as we learn new and innovative techniques. It also evolves with each new
contributor because everyone brings their own unique skills and passions.

include::../startup/what-is-beergarden.adoc[tags=how-can-it-help]

== Before we Start

include::../plugins/python/_includes/prereqs.adoc[]

include::../startup/what-is-beergarden.adoc[tags=terminology]

include::ui-orientation.adoc[]

== Writing Plugins for Beer Garden

After completing this section you will have created a Beer Garden plugin that can be
deployed against an active Beer Garden instance.

include::example-1.adoc[]

include::example-2.adoc[]

include::example-3.adoc[]

include::example-4.adoc[]

include::example-5.adoc[]

== Now What?

Now that you know the basics for creating Beer Garden plugins, it is time to experiment.  Go out and create your own
plugins. Maybe there is a script you run daily for your job and you want to automate it, use Beer Garden. Maybe there
is an analytic that you run monthly to generate a report, use Beer Garden. We will be here to support the community
and provide guidance.

If you want to go the extra mile, have you considered becoming an open source developer yourself?
Beer Garden and many other projects out there need your support and time. Donate your time to
improve something that you have a passion in.
