It is important to be able to tell beer-garden when something on your system goes wrong. `brewtils` takes advantage of Python's exceptions in order to handle command malfunctions. So if you have a function:

[source,python]
----
def my_error(self):
    raise ValueError("Something went wrong!")
----

This will result in the request status turning to "ERROR" and its output will be `Something went wrong!`. It is expected that plugins will throw errors as a way to notify beer-garden that something has gone wrong.

If you choose to handle errors and not throw, you will notice something that may be quite confusing to your plugins users. Let's have an example:

[source,python]
----
def my_error(self, x):
  if x is None:
    # This is actually an error, but we will short-circuit
    return "An error occurred."
  return x
----

If `x` being `None` is an error, then you should throw an error. Otherwise, the request will be marked as `SUCCESS` while the output will say `An error occurred`

If your command has a `JSON` output type, then beer-garden will attempt to format your exception as a JSON error message. Here's an example:

[source,python]
----
@command(command_type="JSON")
def my_error(self):
  raise ValueError("Error Message")
----

If you call this method, you'll still notice a status of `ERROR` but the output will be something like:

```
{
  "message": "Error Message",
  "attributes": {}
}
```

If you're asking what the `attributes` entry is supposed to represent, it will take the `__dict__` of the exception and attempt to jsonify it. Let's say you have a custom exception class like the following:

[source, python]
----
class MyError(Exception):
  def __init__(self, *args, **kwargs):
    self.foo = kwargs.pop("foo")
    self.bar = kwargs.pop("bar")
----

Then you throw that error during a command, beer-garden will modify the output as per the following:

```
{
  "message": "Error Message"
  "attributes": {"foo": "foo_value", "bar": "bar_value"}
}
```

WARNING: If your attributes are not JSON serializable, then a string representation of the dictionary will be provided to the attributes.
