= Contributing to Beer Garden
:uri-snippet: https://gist.github.com
:page-layout: docs


We would love for you to help us make Beer Garden better. Remember, __no contribution is too small__.

== License Agreement
By contributing to any of the Beer Garden repositories, you agree to license your contributions under the {git_group_uri}/beer-garden/blob/master/LICENSE.md[MIT license]. This ensures your contributions have the same license as the project and that the community is free to use your contributions. You also assert that you are the original author of the work you are contributing unless otherwise stated.

== Submitting an Issue

If you have an idea for Beer Garden we want to hear about it. We use the {issues_uri}[issue tracker on GitHub] to track bugs/features. We just ask that before you submit a request or bug you do a quick search to make sure it hasn't already been submitted.

Our ideal feature request comes in with a merge request for a way to implement the feature, but feature requests should at least come with an explanation of how you want the app to behave differently than the current implementation.

If you've found a bug in Beer Garden we would love for you to submit a bug report. When submitting please include a {uri-snippet}[Snippet] that includes any details that may help reproduce the bug. It's also a good idea to include your version of Beer Garden, language, language version and operating system.

Ideal bug reports include a merge request with a failing test.

== Submitting a Pull Request

NOTE: This information is generic on purpose. Each repository in Beer Garden's components will have their own way to run tests. Please refer to the specific project for detailed information on how to write/run tests for that particular project.

1. Fork the repository. This will vary based on what project you are working on.
2. Install the latest development dependencies (usually `make deps`)
3. Create a topic branch (use the pattern `feature/XYZ` where `XYZ` is the
  issue number)
4. Add tests for your unimplemented feature or bug fix.
5. Run the tests, if your tests pass, return to step 4
6. Implement your feature or bug fix
7. Run the tests, if your test fail, return to step 6
8. Add documentation for your feature or bug fix
9. Add, commit, and push your changes.
10. Submit a pull request
