= Beer Garden Manual
:page-layout: docs

The starting point for all your Beer Garden needs!

== Getting Started

Discover Beer Garden and how it can help you.

link:startup/what-is-beergarden/[What is Beer Garden?]::
  A high-level overview of what Beer Garden is exactly and when you should use it

link:startup/quickstart/[Quickstart]::
  A short 5-minute tutorial for getting Beer Garden and a plugin up and running

link:startup/installation-guides/[Installation Guides]::
  Ready to Install Beer Garden? Pick your favorite guide and get started!

== Plugins

All about Beer Garden plugins.

link:plugins/plugin-developer-guide/[Plugin Developer's Guide]::
  A comprehensive tutorial with examples that show you how to write plugins

link:plugins/plugin-syntax-quick-reference/[Plugin Syntax Quick Reference Guide]::
  An overview of the plugin syntax you'll likely need to write a useful plugins

link:plugins/upgrading[Upgrade Guide]::
  Instructions for upgrading plugins from brewtils 2.x to 3.x

== Application

Information about the Beer Garden application and how it works.

link:app/architecture/[Architecture]::
  Learn how Beer Garden internals works

link:app/parent-child[Parent & Child Configurations]::
  Learn how Beer Garden can be configured in a Parent/Child Relationship

link:app/configuration[Configuration Guide]::
  Help with Application configuration

link:app/security[Security Guide]::
  Help with Authentication and Authorization

link:app/api-users-guide/[API Guide]::
    If you aren't writing plugins, but rather using them, this guide is for you

link:app/topics/[Publish/Subscribe Guide]::
  Learn how Pub/Sub is implemented

link:app/upgrading[Upgrade Guide]::
  Instructions for upgrading Beer Garden from 2.x to 3.x

== Github Actions

Beer Garden automates a range of tasks through Github Actions. This is information on what to expect
for each action.

link:app/github-actions#_pull_requests[Pull Request]::
When a Pull Request is submitted, what happens?

link:app/github-actions#_tagging[Tagging]::
When a Tag is creates, what happens? This kicks off our automated release process.

link:app/github-actions#_scheduled_and_integration[Scheduler and Integration]::
What automated actions exist

== Contributing

How to contribute to the Beer Garden project.

link:contributing/#submitting-an-issue[How do I report a bug?]::
  Did you find a bug somewhere in Beer Garden? Checkout how to tell us.

link:contributing/#submitting-an-issue[How do I request a feature?]::
  Do you have the next cool idea for Beer Garden to implement? Tell us about it!

link:contributing/#submitting-a-pull-request[How do I submit code to the project?]::
  If you have code you'd like to contribute, create a pull request!

== Reference and Developer Resources

* {brewtils_docs_uri}[Brewtils (Python) API Documentation]
