= beer-garden
Logan Jones <https://github.com/loganasherjones> @loganasherjones
:idprefix:
:page-layout: docs

Follow the links on this page to learn about beer-garden or plugin development. You'll also find tips on how to be troubleshoot beer-garden and how to write effective, composable plugins with beer-garden syntax.

TIP: Can't find the information you need? Reach out to project members and users via the {chat_uri}[channel] on Slack

== The Basics

Discover beer-garden and how it can help you.

link:what-is-beergarden/[What is beer-garden?]::
  A high-level overview of what beer-garden is exactly and when you should use it

link:user-manual[beer-garden User Manual]::
  The A to Z guide of beer-garden

link:api-users-guide/[API User's Guide]::
    If you aren't writing plugins, but rather using them, this guide is for you

== Get Started with beer-garden

link:installation-guides/[Installation Guides]::
  Ready to Install BEEERGARDEN? Pick your favorite guide and get started!

link:quickstart/[Quickstart]::
  A short 5-minute tutorial for getting beer-garden and a plugin up and running

== Write Plugins with beer-garden

link:plugin-syntax-quick-reference/[Plugin Syntax Quick Reference Guide]::
  An overview of the plugin syntax you'll likely need to write a useful plugin

link:plugin-developer-guide/[Plugin Developer's Guide]::
  A comprehensive tutorial with examples that show you how to write plugins

== beer-garden Architecture

link:architecture/[beer-garden Architecture]::
  Learn how beer-garden works

== Contributing to beer-garden

link:contributing/#submitting-an-issue[How do I report a bug?]::
  Did you find a bug somewhere in beer-garden? Checkout how to tell us.

link:contributing/#submitting-an-issue[How do I request a feature?]::
  Do you have the next cool idea for beer-garden to implement? Tell us about it!

link:contributing/#submitting-a-merge-request[How do I submit code to the project?]::
  If you have code you'd like to contribute, create a merge request!

== Reference and Developer Resources

* {brewtils_docs_uri}[Brewtils (Python) API Documentation]
* {bg_utils_docs_uri}[BG Utils API Documentation]
