= Beer Garden Manual
:page-layout: docs

The starting point for all your Beer Garden needs!

TIP: Can't find the information you need? Reach out to project members and users via {chat_uri}[Gitter]

== Getting Started

Discover Beer Garden and how it can help you.

link:what-is-beergarden/[What is Beer Garden?]::
  A high-level overview of what Beer Garden is exactly and when you should use it

link:quickstart/[Quickstart]::
  A short 5-minute tutorial for getting Beer Garden and a plugin up and running

link:installation-guides/[Installation Guides]::
  Ready to Install Beer Garden? Pick your favorite guide and get started!

== Plugins

All about Beer Garden plugins.

link:plugin-developer-guide/[Plugin Developer's Guide]::
  A comprehensive tutorial with examples that show you how to write plugins

link:plugin-syntax-quick-reference/[Plugin Syntax Quick Reference Guide]::
  An overview of the plugin syntax you'll likely need to write a useful plugins

== Application

Information about the Beer Garden application and how it works.

link:architecture/[Architecture]::
  Learn how Beer Garden internals works

link:docs/configuration[Configuration Guide]::
  Help with Application configuration

link:api-users-guide/[API Guide]::
    If you aren't writing plugins, but rather using them, this guide is for you

== Contributing

How to contribute to the Beer Garden project.

link:contributing/#submitting-an-issue[How do I report a bug?]::
  Did you find a bug somewhere in Beer Garden? Checkout how to tell us.

link:contributing/#submitting-an-issue[How do I request a feature?]::
  Do you have the next cool idea for Beer Garden to implement? Tell us about it!

link:contributing/#submitting-a-pull-request[How do I submit code to the project?]::
  If you have code you'd like to contribute, create a pull request!

== Reference and Developer Resources

* {brewtils_docs_uri}[Brewtils (Python) API Documentation]
