= Beer Garden in 5 minutes
:page-layout: docs
:plugin-include-dir: python/_includes
:install-include-dir: installation-guides/_includes
:plugin-base-image: bgio/plugins:python3

This guide is designed to get you up and running in Beer Garden in the fastest possible way. We will cover, installing Beer Garden and writing your first plugin. Let's dive in!

== Prerequisites

include::{install-include-dir}/docker-prereqs.adoc[]

== Install Beer Garden

We are going to use `docker` and `docker-compose` to install and run Beer Garden.

include::{install-include-dir}/docker-git-clone.adoc[]

include::{install-include-dir}/docker-config-change.adoc[]

include::{install-include-dir}/docker-run-app.adoc[]

== Create your first plugin

Now that Beer Garden is up, let's create a plugin that let's us use Beer Garden! We will create a simple client that will print and return the message passed to it. Change to your workspace and let's start coding!

    mkdir -p $HOME/my_plugin
    cd $HOME/my_plugin

Copy and paste the following code in a file called [x-]`__main__.py`

include::{plugin-include-dir}/complete-plugin.adoc[]

Update `bg_host='YOUR_IP'` to be your own IP address. Now you can simply run your plugin using one of the images we provide!

[source,subs="attributes"]
----
docker run -v $(pwd):/src \
{plugin-base-image}
----

Your plugin is now accessible in the Beer Garden GUI! Click on the `my-plugin` system, and try out the `do_something` command! Fill out whatever message you want and you should see it in the GUI as well as the output from your `docker run` command!

This is just the tip of the iceberg, please feel free to look around the site for more information! Happy brewing!
