= Releasing
:page-layout: docs

This is intended as a guide / checklist for releasing a new versions of Beer Garden things. It's aimed at Beer Garden maintainers.

== Brewtils
Bump the version in `brewtils/\\__version__.py` and update the changelog. Make a new commit with a message that's *only* the new version (this commit message shows up on the Github releases page). Then create and push a new *signed* tag (`git tag -s <version>`) with *only* the version number.

The CI pipeline will run the tests and then build and deploy the source and wheel distributions to pypi.org. It will also build some docker images and deploy them to docker.io.

That's it!

== Application
Bump the version in `src/app/beer_garden/\\__version__.py` and update the changelog.

We *should* also be updating the UI version in `src/ui/package.json`, but since we don't currently deploy that it's not necessary.

Make a new commit with a message that's *only* the new version (this commit message shows up on the Github releases page). Then create and push a new tag with the version number (again, *only* the version number).

The CI pipeline will then:
- Create a Github Release
- Build and deploy the source and wheel distributions to pypi.org
- Use those distributions to build the docker images and deploy them to docker.io
- Build the rpm and upload it to the Github Release as an asset

That's it!

== rpm
You can build the rpm with the `--local` flag, which means "use the version that's locally checked out right now." If you don't specify this flag (the default) then the rpm build process will install the latest versions of "deployed" artifacts (in other words, it will pull the latest `beer-garden` from PyPI).

[CAUTION]
====
Right now we don't actually deploy the UI artifact to npm, so the UI will *always* be built as if the `--local` flag was specified.
====

To build the rpm just run the appropriate `make` target, passing in the version as a build argument:

[source,shell]
----
git clone https://github.com/beer-garden/beer-garden.git
cd beer-garden

# Builds an rpm using the latest published versions of beer-garden and brewtils
make rpm-build VERSION=1.2.3

# Builds an rpm using the local repository
git clone https://github.com/beer-garden/brewtils.git src/brewtils
make rpm-build-local VERSION=1.2.3
----

That will result in a new rpm being created in `beer-garden/rpm/dist/`.

[CAUTION]
====
Be aware this will overwrite any existing files with the same name already in that directory.
====
