= Releasing Beergarden
:page-layout: docs

This is intended as a guide / checklist for releasing a new versions of Beergarden things. It's aimed at the Beergarden
maintainers.

Next MAKE SURE YOU UPDATED THE CHANGELOG.

== Libraries
This one is pretty easy. Applies to these:

- brewtils
- beer-garden

Bump the version in `_version.py`. Make a new commit with a message that's *only* the new version (this commit message
shows up on the Github releases page). Then create and push a new tag with the version number (*only* the version
number - get that extra 'v' out of here).

Travis will run the tests and then build and deploy the source and wheel distributions to pypi.org.

That's it!

== Docker
This works just like the Libraries. Applies to the following to Brewtils, Beer Garden, or Example Plugins repositories.

* bgio/beer-garden
* bgio/ui
* bgio/example-plugins
* bgio/plugins
** bgio/plugins:python2
** bgio/plugins:python3
** bgio/plugins:python2-onbuild
** bgio/plugins:python3-onbuild

Bump the version in `_version.py`. Make a new commit with a message that's *only* the new version (this commit message
shows up on the Github releases page). Then create and push a new tag with the version number (*only* the version
number - get that extra 'v' out of here).

Travis will run the tests and then build and deploy the source and wheel distributions to hub.docker.com.

That's it!

== RPM
This requires some effort. We currently don't have a hosting location for RPMs, so this is manually created each time.

[source,shell script]
----
mkdir rpm-builder;
git clone --branch v3 https://github.com/beer-garden/beer-garden.git rpm-builder/;

mkdir rpm-builder-brewtils;
git clone --branch v3 https://github.com/beer-garden/brewtils.git rpm-builder-brewtils;

mkdir rpm-builder/src/brewtils;
mv rpm-builder-brewtils/* rpm-builder/src/brewtils;

npm --prefix ./rpm-builder/src/ui/ install ./rpm-builder/src/ui/;

rm rpm-builder/src/ui/package-lock.json;
cd rpm-builder/rpm/bin/;

python3 build.py --local --python 3.7 --distribution centos7 rpm 3.0.0;
----
