name: Deploy

on:
  push:
    branches:
      - master

# For Testing Code Only
#on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ruby:2.7.2

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    name: Build and Deploy Beer-Garden.io
    steps:
      - uses: actions/checkout@v2

      # - name: Cache Bundler
      #   uses: actions/cache@v3
      #   with:
      #     path: .cache/bundler
      #     key: ${{ runner.os }}-bundler-${{ hashFiles('**/Gemfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-bundler


      - name: Bundle Install
        run: |
          bundle config set path .cache/bundler
          bundle install

      - name: Build Site
        run: rake gen[github]
        env:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'public'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2

