name: Deploy

#on:
#  push:
#    branches:
#      - master

# For Testing Code Only
on: pull_request

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: Build and Deploy Beer-Garden.io
    steps:
      - uses: actions/checkout@v2

      # Cache is local to the Branch running OR pulled from the Default Branch
      - name: Setup Cache for Ruby
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: -gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            -gems-

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4.1
          #bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Gem Install # Not Required if bundler-cache is true
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Build Site
        run: rake gen[prod]
        env:
          NOKOGIRI_USE_SYSTEM_LIBRARIES: true

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: _site
        env:
          GITHUB_TOKEN: ${{ secrets.BUILDBOT_PAGES }}
